# Generated by Django 3.2.9 on 2021-11-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.CharField(choices=[(1, 'meeting 25/11/2021'), (2, 'meeting 02/12/2021'), (3, 'meeting 09/12/2021')], max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
