# Generated by Django 3.2.9 on 2021-12-10 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=128, unique=True)),
                ('en', models.TextField()),
                ('ua', models.TextField()),
                ('ru', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='meeting',
            field=models.CharField(choices=[('08/12', 'Meeting on 08/12/2021'), ('15/12', 'Meeting on 15/12/2021'), ('22/12', 'Meeting on 22/12/2021')], max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+380XXddddddd'. Up to 13 digits allowed.", regex='^\\+?1?\\d{10,13}$')]),
        ),
    ]
